# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-12 16:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Nutzer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Vorname', models.CharField(max_length=250)),
                ('Nachname', models.CharField(max_length=250)),
                ('Straße', models.CharField(max_length=250)),
                ('Hausnummer', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Sensorkits',
            fields=[
                ('id', models.IntegerField(max_length=100000, primary_key='true', serialize=False)),
                ('Co2', models.FloatField(max_length=200)),
                ('VluftTemp', models.FloatField(max_length=200)),
                ('AbgTemp', models.FloatField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='nutzer',
            name='Sensorkit_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Sensordaten.Sensorkits'),
        ),
    ]
