# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-13 19:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sensordaten', '0002_auto_20161112_1758'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensorkits',
            name='Besitzer',
            field=models.CharField(default='Hans', max_length=200),
        ),
    ]
