# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-14 09:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Sensordaten', '0004_auto_20161114_1035'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nutzer',
            old_name='Sensorkit_id',
            new_name='Sensorkit_nummer',
        ),
    ]
