# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-14 09:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Sensordaten', '0006_auto_20161114_1043'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kunden',
            old_name='Sensorkit_nummer',
            new_name='sensorkit',
        ),
    ]
