# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-14 10:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Sensordaten', '0007_auto_20161114_1046'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kunden',
            old_name='Hausnummer',
            new_name='hausnummer',
        ),
        migrations.RenameField(
            model_name='kunden',
            old_name='Nachname',
            new_name='nachname',
        ),
        migrations.RenameField(
            model_name='kunden',
            old_name='Straße',
            new_name='straße',
        ),
        migrations.RenameField(
            model_name='kunden',
            old_name='Vorname',
            new_name='vorname',
        ),
        migrations.RenameField(
            model_name='sensorkits',
            old_name='AbgTemp',
            new_name='abgTemp',
        ),
        migrations.RenameField(
            model_name='sensorkits',
            old_name='Besitzer',
            new_name='besitzer',
        ),
        migrations.RenameField(
            model_name='sensorkits',
            old_name='Co2',
            new_name='co2',
        ),
        migrations.RenameField(
            model_name='sensorkits',
            old_name='VluftTemp',
            new_name='vluftTemp',
        ),
    ]
