# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-15 14:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Sensordaten', '0008_auto_20161114_1100'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sensorkits',
            name='besitzer',
        ),
    ]
