# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-15 14:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sensordaten', '0009_remove_sensorkits_besitzer'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensorkits',
            name='besitzer',
            field=models.CharField(default='Hans', max_length=200),
        ),
    ]
