# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-17 13:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sensordaten', '0010_sensorkits_besitzer'),
    ]

    operations = [
        migrations.AddField(
            model_name='kunden',
            name='earlybirduser',
            field=models.BooleanField(default=False),
        ),
    ]
