# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-19 10:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sensordaten', '0013_auto_20161117_1437'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kunden',
            name='earlybirduser',
            field=models.BooleanField(default=True),
        ),
    ]
