# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-19 10:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Sensordaten', '0014_auto_20161119_1102'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kunden',
            old_name='earlybirduser',
            new_name='earlybird_user',
        ),
    ]
