# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-19 10:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sensordaten', '0015_auto_20161119_1105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kunden',
            name='earlybird_user',
            field=models.BooleanField(default=False),
        ),
    ]
