# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-19 10:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Sensordaten', '0016_auto_20161119_1107'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kunden',
            name='earlybird_user',
        ),
    ]
