# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-19 10:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sensordaten', '0017_remove_kunden_earlybird_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='kunden',
            name='zahl',
            field=models.FloatField(default=25, max_length=250),
            preserve_default=False,
        ),
    ]
