# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-19 12:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sensordaten', '0018_kunden_zahl'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kunden',
            name='zahl',
        ),
        migrations.AddField(
            model_name='kunden',
            name='earlybirduser',
            field=models.BooleanField(default=False),
        ),
    ]
